[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

; Cấu hình Bộ nhớ chuẩn cho Bo mạch Waveshare ESP32-S3 (8MB PSRAM OPI)
board_build.arduino.memory_type = qio_opi
board_build.f_cpu = 240000000L
board_build.f_flash = 80000000L
board_build.flash_mode = qio

; Bật Native USB CDC để Serial Monitor hiển thị trực tiếp qua cổng USB Type-C trên ESP32-S3
build_flags = 
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1

; Tốc độ theo dõi Serial Monitor
monitor_speed = 115200

; Thư viện Ethernet & JSON
lib_deps =
    https://github.com/jandrassy/Ethernet.git
    bblanchon/ArduinoJson @ ^6.21.3
